"""Generate frontend/src/features/admin/models/provider-catalog.ts from the
local ragflow checkout's conf/llm_factories.json. Re-runnable: refresh by
re-running and committing the output. Maps each ragflow provider onto Ragz's
provider_kind + LiteLLM model prefix, keeping only chat/embedding models."""
import json, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]  # repo root
SRC = ROOT / "ragflow" / "conf" / "llm_factories.json"
OUT = ROOT / "frontend" / "src" / "features" / "admin" / "models" / "provider-catalog.ts"

# ragflow provider name -> (Ragz provider_kind, litellm prefix or "" for bare, base_url or None)
KIND_MAP: dict[str, tuple[str, str, str | None]] = {
    "OpenAI": ("openai", "", None),
    "Azure-OpenAI": ("openai_compatible", "", None),
    "Anthropic": ("litellm", "anthropic", None),
    "Gemini": ("litellm", "gemini", None),
    "Groq": ("litellm", "groq", None),
    "Mistral": ("litellm", "mistral", None),
    "DeepSeek": ("litellm", "deepseek", None),
    "xAI": ("litellm", "xai", None),
    "Cohere": ("litellm", "cohere", None),
    "OpenRouter": ("litellm", "openrouter", None),
    "TogetherAI": ("litellm", "together_ai", None),
    "Bedrock": ("litellm", "bedrock", None),
    "Moonshot": ("litellm", "moonshot", None),
    "MiniMax": ("litellm", "minimax", None),
    "Tongyi-Qianwen": ("litellm", "dashscope", None),
    "ZHIPU-AI": ("litellm", "zhipu", None),
    "Ollama": ("ollama", "", None),
    "LocalAI": ("openai_compatible", "", None),
    "OpenAI-API-Compatible": ("openai_compatible", "", None),
    "VLLM": ("openai_compatible", "", None),
    "Xinference": ("openai_compatible", "", None),
    "Jina": ("litellm", "jina_ai", None),
    "FastEmbed": ("tei", "", None),
    "Builtin": ("tei", "", None),
}
DEFAULT = ("litellm", "", None)  # unknown providers: litellm passthrough, custom-only

def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")

def _model_types(m: dict) -> list[str]:
    # ragflow's model_type is usually a string ("chat") but is sometimes a
    # list (e.g. ["chat", "image2text"]) for multi-modal models; normalize.
    mt = m.get("model_type") or []
    if isinstance(mt, str):
        mt = [mt] if mt else []
    return [str(x).lower() for x in mt]

def is_chat_or_embed(m: dict) -> str | None:
    mt = _model_types(m)
    tags = (m.get("tags") or "").upper()
    if "chat" in mt or "CHAT" in tags or (tags.count("LLM") and "IMAGE2TEXT" not in tags and "embedding" not in mt):
        return "chat"
    if "embedding" in mt or "EMBED" in tags:
        return "embedding"
    return None

def prov_caps(f: dict) -> list[str]:
    t = (f.get("tags") or "").upper()
    caps = []
    if "LLM" in t: caps.append("chat")
    if "EMBEDDING" in t: caps.append("embedding")
    return caps

facs = json.load(open(SRC))
facs = facs["factory_llm_infos"] if isinstance(facs, dict) else facs
providers = []
for f in facs:
    caps = prov_caps(f)
    if not caps:
        continue  # skip pure tts/stt/ocr/moderation providers
    kind, prefix, base = KIND_MAP.get(f["name"], DEFAULT)
    models = []
    for m in (f.get("llm") or []):
        mod = is_chat_or_embed(m)
        if mod is None:
            continue
        raw = m["llm_name"]
        name = f"{prefix}/{raw}" if prefix and "/" not in raw else raw
        entry = {"litellm_model_name": name, "display_name": raw, "modality": mod}
        if "IMAGE2TEXT" in (m.get("tags") or "").upper():
            entry["supports_vision"] = True
        if isinstance(m.get("max_tokens"), int) and m["max_tokens"] > 0:
            entry["context_tokens"] = m["max_tokens"]
        models.append(entry)
    providers.append({
        "id": slug(f["name"]),
        "name": f["name"],
        "provider_kind": kind,
        **({"base_url": base} if base else {}),
        **({"needs_base_url": True} if kind in ("ollama", "openai_compatible") else {}),
        "needs_api_key": kind not in ("ollama", "tei"),
        "capabilities": caps,
        "icon": slug(f["name"]),
        "models": models,
    })

providers.sort(key=lambda p: p["name"].lower())
header = (
    "// GENERATED by frontend/scripts/gen_provider_catalog.py from ragflow's\n"
    "// llm_factories.json. Do not hand-edit; re-run the script to refresh.\n\n"
    "export interface CatalogModel {\n"
    "  litellm_model_name: string;\n  display_name: string;\n"
    "  modality: 'chat' | 'embedding';\n  supports_vision?: boolean;\n"
    "  supports_reasoning?: boolean;\n  context_tokens?: number;\n}\n\n"
    "export interface CatalogProvider {\n"
    "  id: string;\n  name: string;\n"
    "  provider_kind: 'openai' | 'ollama' | 'openai_compatible' | 'litellm' | 'tei';\n"
    "  base_url?: string;\n  needs_base_url?: boolean;\n  needs_api_key: boolean;\n"
    "  capabilities: ('chat' | 'embedding')[];\n  icon: string;\n  models: CatalogModel[];\n}\n\n"
    "export const PROVIDER_CATALOG: CatalogProvider[] = "
)
OUT.write_text(header + json.dumps(providers, indent=2) + ";\n")
print(f"wrote {OUT} with {len(providers)} providers, {sum(len(p['models']) for p in providers)} models")
