"""message stopped and no_answer flags

Revision ID: 0753d7cb5ad5
Revises: 2329cbfbcd7a
Create Date: 2026-07-19 05:39:45.658989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0753d7cb5ad5'
down_revision: Union[str, Sequence[str], None] = '2329cbfbcd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('stopped', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('no_answer', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'no_answer')
    op.drop_column('messages', 'stopped')
    # ### end Alembic commands ###
