"""quotas and usage ledger

Revision ID: 2329cbfbcd7a
Revises: 17b350b251f0
Create Date: 2026-07-19 03:53:50.406343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2329cbfbcd7a'
down_revision: Union[str, Sequence[str], None] = '17b350b251f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_org_created', 'usage_records', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_usage_user_created', 'usage_records', ['user_id', 'created_at'], unique=False)
    op.create_table('org_quotas',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_tokens', sa.Integer(), nullable=False),
    sa.Column('default_user_monthly_tokens', sa.Integer(), nullable=True),
    sa.Column('reset_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('user_quotas',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quotas')
    op.drop_table('org_quotas')
    op.drop_index('ix_usage_user_created', table_name='usage_records')
    op.drop_index('ix_usage_org_created', table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
