"""workspaces

Revision ID: 44357bb74f0c
Revises: 18ae7279d6ec
Create Date: 2026-07-18 05:22:05.495441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44357bb74f0c'
down_revision: Union[str, Sequence[str], None] = '18ae7279d6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('default_model_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_org_id'), 'workspaces', ['org_id'], unique=False)
    op.create_foreign_key(None, 'workspace_members', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_index(op.f('ix_workspaces_org_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
