"""model mock_response

Revision ID: 9cef303b9fb0
Revises: 0753d7cb5ad5
Create Date: 2026-07-19 06:29:24.847553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cef303b9fb0'
down_revision: Union[str, Sequence[str], None] = '0753d7cb5ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('mock_response', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'mock_response')
    # ### end Alembic commands ###
