"""model catalog

Revision ID: aa6a0eb97c23
Revises: 9cef303b9fb0
Create Date: 2026-07-19 08:09:45.916966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6a0eb97c23'
down_revision: Union[str, Sequence[str], None] = '9cef303b9fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_catalog',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('max_input_tokens', sa.Integer(), nullable=True),
    sa.Column('input_cost_per_token', sa.Float(), nullable=True),
    sa.Column('output_cost_per_token', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_catalog')
    # ### end Alembic commands ###
