"""document acl_group_ids

Revision ID: fe89e0733d5b
Revises: 8914c2ad770f
Create Date: 2026-07-19 02:17:29.136543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe89e0733d5b'
down_revision: Union[str, Sequence[str], None] = '8914c2ad770f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('acl_group_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'acl_group_ids')
    # ### end Alembic commands ###
